export const WORDS_LIST = [
  'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'it',
  'for', 'not', 'on', 'with', 'he', 'as', 'you', 'do', 'at', 'this',
  'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her', 'she', 'or',
  'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their', 'what', 'so',
  'up', 'out', 'if', 'about', 'who', 'get', 'which', 'go', 'me', 'when',
  'make', 'can', 'like', 'time', 'no', 'just', 'him', 'know', 'take', 'people',
  'into', 'year', 'your', 'good', 'some', 'could', 'them', 'see', 'other', 'than',
  'then', 'now', 'look', 'only', 'come', 'its', 'over', 'think', 'also', 'back',
  'after', 'use', 'two', 'how', 'our', 'work', 'first', 'well', 'way', 'even',
  'new', 'want', 'because', 'any', 'these', 'give', 'day', 'most', 'us', 'love',
  'joy', 'hope', 'best', 'sun', 'sky', 'tree', 'bird', 'star', 'life', 'mind',
  'soul', 'free', 'kind', 'pure', 'true', 'calm', 'safe', 'warm', 'cool', 'fast',
  'run', 'walk', 'sit', 'stand', 'eat', 'drink', 'sleep', 'wake', 'play', 'read',
  'write', 'talk', 'listen', 'watch', 'look', 'feel', 'touch', 'smell', 'taste', 'happy',
  'sad', 'angry', 'scared', 'brave', 'smart', 'dumb', 'big', 'small', 'tall', 'short',
  'fat', 'thin', 'hot', 'cold', 'wet', 'dry', 'hard', 'soft', 'light', 'dark',
  'red', 'blue', 'green', 'yellow', 'black', 'white', 'brown', 'pink', 'purple', 'orange',
  'gray', 'boy', 'girl', 'man', 'woman', 'child', 'baby', 'dog', 'cat', 'fish',
  'bird', 'cow', 'pig', 'horse', 'sheep', 'lion', 'tiger', 'bear', 'wolf', 'fox',
  'deer', 'mouse', 'rat', 'snake', 'frog', 'bug', 'ant', 'bee', 'fly', 'car',
  'bus', 'train', 'boat', 'ship', 'plane', 'bike', 'door', 'window', 'wall', 'floor',
  'roof', 'room', 'bed', 'chair', 'table', 'desk', 'pen', 'book', 'page', 'word',
  'line', 'art', 'map', 'hat', 'coat', 'shoe', 'sock', 'shirt', 'pants', 'dress',
  'skirt', 'ring', 'watch', 'bag', 'box', 'cup', 'plate', 'bowl', 'fork', 'spoon',
  'knife', 'pan', 'pot', 'food', 'meat', 'milk', 'egg', 'bread', 'cake', 'pie',
  'apple', 'pear', 'plum', 'grape', 'corn', 'bean', 'rice'
];

export const WORDS_LIST_MEDIUM = [
  'beautiful', 'important', 'language', 'different', 'sometimes', 'children', 'question', 'together', 'sentence', 'building',
  'possible', 'something', 'remember', 'mountain', 'business', 'complete', 'measure', 'product', 'machine', 'science',
  'decided', 'surface', 'produce', 'nothing', 'general', 'equation', 'material', 'syllable', 'suddenly', 'direction',
  'programming', 'developer', 'keyboard', 'accuracy', 'challenge', 'practice', 'function', 'variable', 'computer', 'software',
  'hardware', 'increase', 'achieve', 'success', 'passion', 'journey', 'believe', 'courage', 'purpose', 'inspire',
  'freedom', 'harmony', 'balance', 'growth', 'strength', 'wisdom', 'nature', 'forest', 'ocean', 'river',
  'desert', 'weather', 'animal', 'planet', 'morning', 'evening', 'family', 'friend', 'society', 'history',
  'culture', 'music', 'energy', 'system', 'method', 'design', 'network', 'project', 'ability', 'absence',
  'academy', 'account', 'accuse', 'achieve', 'acquire', 'address', 'advance', 'adverse', 'advise', 'advisor',
  'advocate', 'affair', 'affect', 'afford', 'against', 'airline', 'airport', 'alcohol', 'alleged', 'already',
  'analyst', 'analyze', 'ancient', 'another', 'answer', 'anxiety', 'anxious', 'anybody', 'anymore', 'anyway',
  'apology', 'apparent', 'appeal', 'appear', 'appetite', 'applaud', 'apple', 'appoint', 'appreciate', 'approach',
  'approve', 'approximate', 'architect', 'archive', 'area', 'argue', 'arise', 'army', 'around', 'arrange',
  'arrest', 'arrive', 'arrow', 'article', 'artist', 'aspect', 'assault', 'assert', 'assess', 'asset',
  'assign', 'assist', 'assume', 'assure', 'athlete', 'athletic', 'atmosphere', 'attach', 'attack', 'attempt',
  'attend', 'attention', 'attitude', 'attract', 'attribute', 'audience', 'author', 'authority', 'auto', 'available',
  'average', 'avoid', 'award', 'aware', 'awareness', 'away', 'awful', 'baby', 'back', 'background',
  'badly', 'bake', 'balance', 'ball', 'balloon', 'ballot', 'banana', 'band', 'bank', 'banker',
  'banking', 'bar', 'barely', 'barrel', 'barrier', 'base', 'baseball', 'basic', 'basically', 'basis',
  'basket', 'basketball', 'bathroom', 'battery', 'battle', 'beach', 'bear', 'beat', 'beautiful', 'beauty',
  'because', 'become', 'bed', 'bedroom', 'beer', 'before', 'begin', 'beginning', 'behavior', 'behind',
  'being', 'belief', 'believe', 'bell', 'belong', 'below', 'belt', 'bench', 'bend', 'beneath',
  'benefit', 'beside', 'besides', 'best', 'bet', 'better', 'between', 'beyond', 'bicycle', 'bill',
  'billion', 'bind', 'biological', 'bird', 'birth', 'birthday', 'bite', 'black', 'blade', 'blame',
  'blanket', 'blind', 'block', 'blood', 'blow', 'blue', 'board', 'boat', 'body', 'bomb',
  'bombing', 'bond', 'bone', 'book', 'boom', 'boot', 'border', 'born', 'borrow', 'boss',
  'both', 'bother', 'bottle', 'bottom', 'boundary', 'bowl', 'box', 'boy', 'boyfriend', 'brain',
  'branch', 'brand', 'bread', 'break', 'breakfast', 'breast', 'breath', 'breathe', 'brick', 'bridge',
  'brief', 'briefly', 'bright', 'brilliant', 'bring', 'British', 'broad', 'broken', 'brother', 'brown',
  'brush', 'buck', 'budget', 'build', 'building', 'bullet', 'bunch', 'burden', 'burn', 'bury',
  'bus', 'business', 'busy', 'butter', 'button', 'buy', 'buyer', 'by', 'cabin', 'cabinet',
  'cable', 'cake', 'calculate', 'call', 'camera', 'camp', 'campaign', 'campus', 'can', 'Canadian',
  'cancer', 'candidate', 'cap', 'capability', 'capable', 'capacity', 'capital', 'captain', 'capture', 'car',
  'carbon', 'card', 'care', 'career', 'careful', 'carefully', 'carrier', 'carry', 'case', 'cash',
  'cast', 'cat', 'catch', 'category', 'Catholic', 'cause', 'ceiling', 'celebrate', 'celebration', 'celebrity',
  'cell', 'center', 'central', 'century', 'CEO', 'ceremony', 'certain', 'certainly', 'chain', 'chair',
  'chairman', 'challenge', 'chamber', 'champion', 'championship', 'chance', 'change', 'changing', 'channel', 'chapter',
  'character', 'characteristic', 'characterize', 'charge', 'charity', 'chart', 'chase', 'cheap', 'check', 'cheek',
  'cheese', 'chef', 'chemical', 'chest', 'chicken', 'chief', 'child', 'childhood', 'Chinese', 'chip',
  'chocolate', 'choice', 'cholesterol', 'choose', 'Christian', 'Christmas', 'church', 'cigarette', 'circle', 'circumstance',
  'cite', 'citizen', 'city', 'civil', 'civilian', 'claim', 'class', 'classic', 'classroom', 'clean',
  'clear', 'clearly', 'client', 'climate', 'climb', 'clinic', 'clinical', 'clock', 'close', 'closely',
  'closer', 'clothes', 'clothing', 'cloud', 'club', 'clue', 'cluster', 'coach', 'coal', 'coalition',
  'coast', 'coat', 'code', 'coffee', 'cognitive', 'cold', 'collapse', 'colleague', 'collect', 'collection',
  'collective', 'college', 'colonial', 'color', 'column', 'combination', 'combine', 'come', 'comedy', 'comfort',
  'comfortable', 'command', 'commander', 'comment', 'commercial', 'commission', 'commit', 'commitment', 'committee', 'common',
  'communicate', 'communication', 'community', 'company', 'compare', 'comparison', 'compete', 'competition', 'competitive', 'competitor',
  'complain', 'complaint', 'complete', 'completely', 'complex', 'complicated', 'component', 'compose', 'composition', 'comprehensive',
  'computer', 'concentrate', 'concentration', 'concept', 'concern', 'concerned', 'concert', 'conclude', 'conclusion', 'concrete',
  'condition', 'conduct', 'conference', 'confidence', 'confident', 'confirm', 'conflict', 'confront', 'confusion', 'Congress',
  'congressional', 'connect', 'connection', 'consciousness', 'consensus', 'sequence', 'conservative', 'consider', 'considerable', 'consideration',
  'consist', 'consistent', 'constant', 'constantly', 'constitute', 'constitutional', 'construct', 'construction', 'consultant', 'consume',
  'consumer', 'consumption', 'contact', 'contain', 'container', 'contemporary', 'content', 'contest', 'context', 'continue',
  'continued', 'contract', 'contrast', 'contribute', 'contribution', 'control', 'controversial', 'controversy', 'convention', 'conventional',
  'conversation', 'convert', 'conviction', 'convince', 'cook', 'cookie', 'cooking', 'cool', 'cooperation', 'cop',
  'cope', 'copy', 'core', 'corn', 'corner', 'corporate', 'corporation', 'correct', 'correspondent', 'cost',
  'cotton', 'couch', 'could', 'council', 'counselor', 'count', 'counter', 'country', 'county', 'couple',
  'courage', 'course', 'court', 'cousin', 'cover', 'coverage', 'cow', 'crack', 'craft', 'crash',
  'crazy', 'cream', 'create', 'creation', 'creative', 'creature', 'credit', 'crew', 'crime', 'criminal',
  'crisis', 'criteria', 'critic', 'critical', 'criticism', 'criticize', 'crop', 'cross', 'crowd', 'crucial',
  'cry', 'cultural', 'culture', 'cup', 'curious', 'current', 'currently', 'curriculum', 'custom', 'customer',
  'cut', 'cycle'
];

export const WORDS_LIST_HARD = [
  'phenomenon', 'exacerbate', 'unprecedented', 'synergistic', 'paradigm', 'juxtaposition', 'ubiquitous', 'ephemeral', 'cacophony', 'idiosyncrasy',
  'conundrum', 'facetious', 'serendipity', 'ostentatious', 'pragmatic', 'ambiguous', 'inexorable', 'meticulous', 'esoteric', 'procrastinate',
  'obfuscate', 'clandestine', 'quintessential', 'perfunctory', 'fastidious', 'magnanimous', 'recalcitrant', 'perspicacious', 'pusillanimous', 'quixotic',
  'surreptitious', 'truculent', 'vociferous', 'sagacious', 'resilience', 'perseverance', 'determination', 'transcendental', 'enlightenment', 'philosophical',
  'biodiversity', 'meteorological', 'extraterrestrial', 'photosynthesis', 'architecture', 'cryptography', 'asynchronous', 'polymorphism', 'encapsulation', 'infrastructure',
  'aberration', 'abstemious', 'acumen', 'admonish', 'adulterate', 'aesthetic', 'alacrity', 'amalgamate', 'ameliorate', 'anachronism',
  'analogous', 'anathema', 'anomaly', 'antipathy', 'apathy', 'apocryphal', 'apostate', 'appropriate', 'arcane', 'archaic',
  'arduous', 'articulate', 'ascetic', 'asperity', 'assuage', 'audacious', 'austere', 'avarice', 'axiom', 'banal',
  'bellicose', 'beneficent', 'bolster', 'bombastic', 'boorish', 'burgeon', 'burnish', 'buttress', 'cacophony', 'candid',
  'capricious', 'castigate', 'catalyst', 'caustic', 'chicanery', 'coagulate', 'cogent', 'commensurate', 'compendium', 'complaisant',
  'conciliatory', 'confound', 'connoisseur', 'contention', 'contentious', 'contrite', 'conundrum', 'converge', 'convoluted', 'craven',
  'daunt', 'decorum', 'default', 'deference', 'delineate', 'denigrate', 'deride', 'derivative', 'desiccate', 'desultory',
  'deterrent', 'diatribe', 'dichotomy', 'diffidence', 'diffuse', 'digression', 'dirge', 'disabuse', 'discern', 'discordant',
  'discredit', 'discrepancy', 'discrete', 'disingenuous', 'disinterested', 'disjointed', 'dismiss', 'disparage', 'disparate', 'dissemble',
  'disseminate', 'dissolution', 'dissonance', 'distend', 'distill', 'diverge', 'divest', 'document', 'dogmatic', 'dormant',
  'dupe', 'ebullient', 'eclectic', 'efficacy', 'effrontery', 'elegy', 'elicit', 'embellish', 'empirical', 'emulate',
  'endemic', 'enervate', 'engender', 'enhance', 'enigma', 'ephemeral', 'equanimity', 'equivocate', 'erudite', 'esoteric',
  'eulogy', 'euphemism', 'exacerbate', 'exculpate', 'exigency', 'extrapolation', 'facetious', 'facilitate', 'fallacious', 'fatuous',
  'fawning', 'felicitous', 'fervor', 'flag', 'fledgling', 'flout', 'foment', 'forestall', 'fortuitous', 'frugality',
  'futile', 'gainsay', 'garrulous', 'goad', 'gouge', 'grandiloquent', 'gregarious', 'guileless', 'gullible', 'halcyon',
  'harangue', 'heterogeneous', 'homogeneous', 'hyperbole', 'iconoclastic', 'idolatry', 'immutable', 'impair', 'impassive', 'impede',
  'impermeable', 'imperturbable', 'impervious', 'implacable', 'implicit', 'implode', 'inadvertently', 'inchoate', 'incongruity', 'inconsequential',
  'incorporate', 'indeterminate', 'indigence', 'indolent', 'inert', 'ingenuous', 'inherent', 'innocuous', 'insensible', 'insinuate',
  'insipid', 'insularity', 'intractable', 'intransigence', 'inundate', 'inured', 'invective', 'irascible', 'irresolute', 'itinerary',
  'laconic', 'lassitude', 'latent', 'laud', 'lethargic', 'levee', 'levity', 'log', 'loquacious', 'lucid',
  'luminous', 'magnanimity', 'malingerer', 'malleable', 'maverick', 'mendacious', 'metamorphosis', 'meticulous', 'misanthrope', 'mitigate',
  'mollify', 'morose', 'mundane', 'negate', 'neophyte', 'obdurate', 'obsequious', 'obviate', 'occlude', 'officious',
  'onerous', 'opprobrium', 'oscillate', 'ostentatious', 'paragon', 'partisan', 'pathological', 'paucity', 'pedantic', 'penchant',
  'penury', 'perennial', 'perfidious', 'perfunctory', 'permeable', 'pervasive', 'phlegmatic', 'piety', 'placate', 'plasticity',
  'platitude', 'plethora', 'plummet', 'porous', 'pragmatic', 'preamble', 'precarious', 'precipitate', 'precursor', 'presumptuous',
  'prevaricate', 'pristine', 'probity', 'problematic', 'prodigal', 'profound', 'prohibitive', 'proliferate', 'propensity', 'propitiate',
  'propriety', 'proscribe', 'pungent', 'qualified', 'quibble', 'quiescent', 'rarefied', 'recalcitrant', 'recant', 'reclusive',
  'recondite', 'redoubtable', 'refractory', 'refute', 'relegate', 'reproach', 'reprobate', 'repudiate', 'rescind', 'resolution',
  'resolve', 'reticent', 'reverent', 'sage', 'salubrious', 'sanction', 'satiate', 'saturate', 'savor', 'secrete',
  'shard', 'skeptic', 'solicitous', 'soporific', 'specious', 'spectrum', 'sporadic', 'stigma', 'stint', 'stipulate',
  'stolid', 'striated', 'strut', 'subpoena', 'subside', 'substantiate', 'supersede', 'supposition', 'tacit', 'taciturn',
  'tangential', 'tenuous', 'tirade', 'torpor', 'tortuous', 'tractable', 'transgression', 'truculence', 'vacillate', 'venerate',
  'veracious', 'verbose', 'viable', 'viscous', 'vituperative', 'volatile', 'warranted', 'wary', 'welter', 'whimsical',
  'zealot'
];

export const WORDS_LIST_HINGLISH_EASY = [
  'aur', 'kya', 'hai', 'ho', 'tu', 'tum', 'hum', 'woh', 'yeh', 'main',
  'aap', 'ek', 'do', 'haan', 'na', 'aaj', 'kal', 'ab', 'kab', 'jab',
  'tab', 'din', 'raat', 'ghar', 'kuch', 'sab', 'bas', 'hi', 'to', 'bhi',
  'se', 'ke', 'ki', 'ko', 'ne', 'par', 'mein', 'liye', 'saath', 'paas',
  'door', 'upar', 'neeche', 'aage', 'peeche', 'andar', 'bahar', 'yahan', 'wahan', 'kahan',
  'jahan', 'tahan', 'idhar', 'udhar', 'kidhar', 'jidhar', 'tidhar', 'aise', 'waise', 'kaise',
  'jaise', 'taise', 'itna', 'utna', 'kitna', 'jitna', 'titna', 'kaisa', 'jaisa', 'waisa',
  'aisa', 'taisa', 'koi', 'jo', 'wo', 'ye', 'un', 'in', 'us', 'is',
  'tumhara', 'hamara', 'mera', 'tera', 'uska', 'iska', 'unka', 'inka', 'apna', 'mujhe',
  'tujhe', 'use', 'ise', 'unhe', 'inhe', 'humein', 'tumhein', 'mujh', 'tujh', 'apne',
  'bada', 'chhota', 'acha', 'bura', 'lamba', 'chauda', 'gora', 'kala', 'naya', 'purana',
  'sasta', 'mahnga', 'thanda', 'garam', 'mitha', 'khatta', 'kadwa', 'safed', 'halki', 'bhaari',
  'tej', 'dheere', 'jaldi', 'der', 'sahi', 'galat', 'kam', 'zyada', 'pyaas', 'bhookh',
  'neend', 'aankh', 'kaan', 'naak', 'muh', 'haath', 'pair', 'baal', 'sir', 'pet',
  'peeth', 'dil', 'jaan', 'rooh', 'khoon', 'paani', 'aag', 'hawa', 'maati', 'dhool',
  'kachra', 'ganda', 'saaf', 'kapda', 'joota', 'chappal', 'ghadi', 'chashma', 'kitab', 'kalam',
  'kagaz', 'mez', 'kursi', 'palang', 'bistar', 'kamra', 'rasoi', 'bathroom', 'chhat', 'farsh',
  'darwaza', 'khidki', 'bijli', 'pankha', 'bulb', 'tv', 'phone', 'gadi', 'scooter', 'cycle',
  'bus', 'train', 'rastay', 'gali', 'mohalla', 'shehar', 'gaon', 'desh', 'duniya', 'asmaan',
  'zameen', 'suraj', 'chaand', 'taara', 'baadal', 'baarish', 'hawa', 'toofan', 'thand', 'garmi',
  'mausam', 'saal', 'mahina', 'hafta', 'din', 'raat', 'subah', 'shaam', 'dopahar', 'samay',
  'ghanta', 'minute', 'second', 'pal', 'aaj', 'kal', 'parso', 'narso', 'tarso', 'roz',
  'kabhi', 'hamesha', 'aksar', 'shayad', 'zaroor', 'bilkul', 'waise'
];

export const WORDS_LIST_HINGLISH_MEDIUM = [
  'kaise', 'theek', 'hoon', 'batao', 'bhai', 'yaar', 'milte', 'hain', 'kahaan', 'yahaan',
  'wahaan', 'nahi', 'acha', 'chalo', 'chahiye', 'kar', 'karna', 'kiya', 'karo', 'karein',
  'rakh', 'rakhna', 'rakha', 'rakho', 'de', 'dena', 'diya', 'do', 'le', 'lena',
  'liya', 'lo', 'aa', 'aana', 'aaya', 'aao', 'ja', 'jaana', 'gaya', 'jao',
  'khaa', 'khaana', 'khaaya', 'khao', 'pee', 'peena', 'piya', 'piyo', 'so', 'sona',
  'soya', 'soo', 'utha', 'uthna', 'uth', 'utho', 'baith', 'baithna', 'baitha', 'baitho',
  'chal', 'chalna', 'chala', 'chalo', 'daud', 'daudna', 'dauda', 'daudo', 'khel', 'khelna',
  'khela', 'khelo', 'padh', 'padhna', 'padha', 'padho', 'likh', 'likhna', 'likha', 'likho',
  'sun', 'sunna', 'suna', 'suno', 'bol', 'bolna', 'bola', 'bolo', 'bata', 'batana',
  'bataya', 'batao', 'pooch', 'poochna', 'poocha', 'poocho', 'dekh', 'dekhna', 'dekha', 'dekho',
  'samajh', 'samajhna', 'samjha', 'samjho', 'soch', 'sochna', 'socha', 'socho', 'bana', 'banana',
  'banaya', 'banao', 'tod', 'todna', 'toda', 'todo', 'jod', 'jodna', 'joda', 'jodo',
  'khol', 'kholna', 'khola', 'kholo', 'band', 'kar', 'ro', 'rona', 'roya', 'roo',
  'hans', 'hansna', 'hansa', 'hanso', 'muskura', 'muskurana', 'muskuraya', 'muskurao', 'gaa', 'gaana',
  'gaaya', 'gao', 'naach', 'naachna', 'naacha', 'naacho', 'kood', 'koodna', 'kooda', 'koodo',
  'gir', 'girna', 'gira', 'giro', 'bach', 'bachna', 'bacha', 'bacho', 'maar', 'maarna',
  'maara', 'maaro', 'peet', 'peetna', 'peeta', 'peeto', 'lad', 'ladna', 'lada', 'lado',
  'jeet', 'jeetna', 'jeeta', 'jeeto', 'haar', 'haarna', 'haara', 'haaro', 'mil', 'milna',
  'mila', 'milo', 'kho', 'khona', 'khoya', 'khoo', 'paa', 'paana', 'paaya', 'pao',
  'dhoond', 'dhoondna', 'dhoonda', 'dhoondo', 'pakad', 'pakadna', 'pakda', 'pakdo', 'chhod', 'chhodna',
  'chhoda', 'chhodo', 'rakh', 'rakhna', 'rakha', 'rakho', 'uth', 'uthna', 'utha', 'utho',
  'baith', 'baithna', 'baitha', 'baitho', 'le', 'lena', 'liya', 'lo', 'de', 'dena',
  'diya', 'do', 'bahut', 'dost', 'pyaar', 'khushi', 'dard', 'kabhi', 'waqt', 'samay',
  'sach', 'jhooth', 'kaam', 'maza', 'paani', 'khana', 'subah', 'shaam', 'baat', 'karte',
  'aise', 'waise', 'aawaz', 'shor', 'shaanti', 'gussa', 'pyaar', 'dosti', 'dushmani', 'nafrat',
  'bharosa', 'dhokha', 'sachai', 'imandari', 'beimani', 'kismat', 'bhagya', 'naseeb', 'taqdeer', 'dua',
  'baddua', 'aashirwad', 'prarthana', 'puja', 'namaz', 'mandir', 'masjid', 'girjagar', 'gurudwara', 'dharam',
  'imaan', 'paap', 'punya', 'swarg', 'narak', 'bhagwan', 'khuda', 'allah', 'rab', 'ishwar',
  'prabhu', 'devta', 'devi', 'bhoot', 'chudail', 'raakshas', 'pari', 'farishta', 'jaadu', 'tonaa',
  'totka', 'shagun', 'apshagun'
];

export const WORDS_LIST_HINGLISH_HARD = [
  'zindagi', 'hamesha', 'koshish', 'kamyabi', 'manzil', 'raasta', 'ummeed', 'sapne', 'dimag', 'duniya',
  'mehnat', 'padhai', 'shukriya', 'samajh', 'badhiya', 'khubsurat', 'mohabbat', 'takleef', 'mushkil', 'pareshani',
  'jazbaat', 'vishwas', 'ehsaas', 'nazariya', 'parivar', 'rishtey', 'zimmedari', 'farz', 'kartavya', 'haq',
  'adhikaar', 'insaf', 'nyaay', 'insaaniyat', 'sharafat', 'badmashi', 'gunda', 'mawali', 'chor', 'lutera',
  'daku', 'qatil', 'khooni', 'mujrim', 'apradhi', 'qaidi', 'jail', 'kaid', 'saza', 'riha',
  'azaad', 'azaadi', 'swatantrata', 'gulaam', 'gulaami', 'naukar', 'maalik', 'seth', 'raja', 'rani',
  'wazir', 'sipahi', 'sena', 'fauj', 'jung', 'yuddh', 'ladai', 'jhagda', 'vivad', 'samjhauta',
  'sulaha', 'dosti', 'dushman', 'mitra', 'shatru', 'saathi', 'sangee', 'hamsafar', 'humdard', 'humraaz',
  'jaaneman', 'mehboob', 'aashiq', 'maashooq', 'deewana', 'pagal', 'majnu', 'laila', 'heer', 'ranjha',
  'romeo', 'juliet', 'kahaani', 'kissa', 'dastaan', 'afsana', 'ghazal', 'nazm', 'kavita', 'geet',
  'sangeet', 'dhun', 'sur', 'taal', 'raaga', 'nritya', 'naach', 'kala', 'fann', 'hunar',
  'kamaal', 'dhamaal', 'bawaal', 'tehelka', 'toofan', 'bhookamp', 'zalzala', 'baadh', 'sookha', 'akaal',
  'mahamaari', 'bimari', 'ilaaj', 'dawa', 'daroo', 'sharab', 'nasha', 'hosh', 'behosh', 'pagalpan',
  'deewangi', 'junoon', 'shauq', 'zidd', 'hath', 'ahankar', 'ghamand', 'gurur', 'swabhiman', 'izzat',
  'aabroo', 'sharam', 'haya', 'lihaaz', 'adab', 'tameez', 'tehzeeb', 'sanskar', 'parampara', 'riwaaz',
  'pratha', 'riti', 'reet', 'rwaaj', 'tyohar', 'utsav', 'mela', 'jalsa', 'mehfil', 'shadi',
  'byaah', 'nikaah', 'mangni', 'sagai', 'rishta', 'naata', 'sambandh', 'talluq', 'jaan', 'pehchaan',
  'mulaqat', 'bhent', 'darshan', 'nazara', 'drishya', 'manzar', 'mausam', 'fiza', 'hawa', 'rut',
  'bahar', 'patjhad', 'sardi', 'garmi', 'barsaat'
];

export const WORDS_LIST_HINDI_EASY = [
  'और', 'क्या', 'है', 'हो', 'तू', 'तुम', 'हम', 'वह', 'यह', 'मैं',
  'आप', 'एक', 'दो', 'हाँ', 'ना', 'आज', 'कल', 'अब', 'कब', 'जब',
  'तब', 'दिन', 'रात', 'घर', 'कुछ', 'सब', 'बस', 'ही', 'तो', 'भी',
  'से', 'के', 'की', 'को', 'ने', 'पर', 'में', 'लिए', 'साथ', 'पास',
  'दूर', 'ऊपर', 'नीचे', 'आगे', 'पीछे', 'अंदर', 'बाहर', 'यहाँ', 'वहाँ', 'कहाँ',
  'जहाँ', 'तहाँ', 'इधर', 'उधर', 'किधर', 'जिधर', 'तिधर', 'ऐसे', 'वैसे', 'कैसे',
  'जैसे', 'तैसे', 'इतना', 'उतना', 'कितना', 'जितना', 'तितना', 'कैसा', 'जैसा', 'वैसा',
  'ऐसा', 'तैसा', 'कोई', 'जो', 'वो', 'ये', 'उन', 'इन', 'उस', 'इस',
  'तुम्हारा', 'हमारा', 'मेरा', 'तेरा', 'उसका', 'इसका', 'उनका', 'इनका', 'अपना', 'मुझे',
  'तुझे', 'उसे', 'इसे', 'उन्हें', 'इन्हें', 'हमें', 'तुम्हें', 'मुझ', 'तुझ', 'अपने',
  'बड़ा', 'छोटा', 'अच्छा', 'बुरा', 'लंबा', 'चौड़ा', 'गोरा', 'काला', 'नया', 'पुराना',
  'सस्ता', 'महंगा', 'ठंडा', 'गरम', 'मीठा', 'खट्टा', 'कड़वा', 'सफ़ेद', 'हल्का', 'भारी',
  'तेज़', 'धीरे', 'जल्दी', 'देर', 'सही', 'ग़लत', 'कम', 'ज़्यादा', 'प्यास', 'भूख',
  'नींद', 'आँख', 'कान', 'नाक', 'मुँह', 'हाथ', 'पैर', 'बाल', 'सिर', 'पेट',
  'पीठ', 'दिल', 'जान', 'रूह', 'खून', 'पानी', 'आग', 'हवा', 'माटी', 'धूल',
  'कचरा', 'गंदा', 'साफ़', 'कपड़ा', 'जूता', 'चप्पल', 'घड़ी', 'चश्मा', 'किताब', 'कलम',
  'कागज़', 'मेज़', 'कुर्सी', 'पलंग', 'बिस्तर', 'कमरा', 'रसोई', 'बाथरूम', 'छत', 'फ़र्श',
  'दरवाज़ा', 'खिड़की', 'बिजली', 'पंख', 'बल्ब', 'टीवी', 'फ़ोन', 'गाड़ी', 'स्कूटर', 'साइकिल',
  'बस', 'ट्रेन', 'रास्ता', 'गली', 'मोहल्ला', 'शहर', 'गाँव', 'देश', 'दुनिया', 'आसमान',
  'ज़मीन', 'सूरज', 'चाँद', 'तारा', 'बादल', 'बारिश', 'तूफ़ान', 'ठंड', 'गर्मी', 'मौसम',
  'साल', 'महीना', 'हफ़्ता', 'दिन', 'रात', 'सुबह', 'शाम', 'दोपहर', 'समय', 'घंटा',
  'मिनट', 'सेकंड', 'पल', 'आज', 'कल', 'परसों', 'नरसों', 'तरसों', 'रोज़', 'कभी',
  'हमेशा', 'अक्सर', 'शायद', 'ज़रूर', 'बिल्कुल', 'वैसे'
];

export const WORDS_LIST_HINDI_MEDIUM = [
  'कैसे', 'ठीक', 'हूँ', 'बताओ', 'भाई', 'यार', 'मिलते', 'हैं', 'कहाँ', 'यहाँ',
  'वहाँ', 'नहीं', 'अच्छा', 'चलो', 'बहुत', 'दोस्त', 'प्यार', 'ख़ुशी', 'दर्द', 'कभी',
  'वक्त', 'समय', 'सच', 'झूठ', 'काम', 'मज़ा', 'खेल', 'पानी', 'खाना', 'सुबह',
  'शाम', 'बात', 'करते', 'ऐसे', 'वैसे', 'आवाज़', 'शोर', 'शांति', 'गुस्सा', 'दोस्ती',
  'दुश्मनी', 'नफ़रत', 'भरोसा', 'धोखा', 'सच्चाई', 'ईमानदारी', 'बेईमानी', 'किस्मत', 'भाग्य', 'नसीब',
  'तकदीर', 'दुआ', 'बद्दुआ', 'आशीर्वाद', 'प्रार्थना', 'पूजा', 'नमाज़', 'मंदिर', 'मस्जिद', 'गिरजाघर',
  'गुरुद्वारा', 'धरम', 'ईमान', 'पाप', 'पुण्य', 'स्वर्ग', 'नरक', 'भगवान', 'खुदा', 'अल्लाह',
  'रब', 'ईश्वर', 'प्रभु', 'देवता', 'देवी', 'भूत', 'चुड़ैल', 'राक्षस', 'परी', 'फ़रिश्ता',
  'जादू', 'टोना', 'टोटका', 'शगुन', 'अपशगुन', 'चाहिए', 'कर', 'करना', 'किया', 'करो',
  'करें', 'रख', 'रखना', 'रखा', 'रखो', 'दे', 'देना', 'दिया', 'दो', 'ले',
  'लेना', 'लिया', 'लो', 'आ', 'आना', 'आया', 'आओ', 'जा', 'जाना', 'गया',
  'जाओ', 'खा', 'खाना', 'खाया', 'खाओ', 'पी', 'पीना', 'पिया', 'पियो', 'सो',
  'सोना', 'सोया', 'सोओ', 'उठा', 'उठना', 'उठ', 'उठो', 'बैठ', 'बैठना', 'बैठा',
  'बैठो', 'चल', 'चलना', 'चला', 'चलो', 'दौड़', 'दौड़ना', 'दौड़ा', 'दौड़ो', 'खेल',
  'खेलना', 'खेला', 'खेलो', 'पढ़', 'पढ़ना', 'पढ़ा', 'पढ़ो', 'लिख', 'लिखना', 'लिखा',
  'लिखो', 'सुन', 'सुनना', 'सुना', 'सुनो', 'बोल', 'बोलना', 'बोला', 'बोलो', 'बता',
  'बताना', 'बताया', 'बताओ', 'पूछ', 'पूछना', 'पूछा', 'पूछो', 'देख', 'देखना', 'देखा',
  'देखो', 'समझ', 'समझना', 'समझा', 'समझो', 'सोच', 'सोचना', 'सोचा', 'सोचो', 'बना',
  'बनाना', 'बनाया', 'बनाओ', 'तोड़', 'तोड़ना', 'तोड़ा', 'तोड़ो', 'जोड़', 'जोड़ना', 'जोड़ा',
  'जोड़ो', 'खोल', 'खोलना', 'खोला', 'खोलो', 'बंद', 'रो', 'रोना', 'रोया', 'हंस',
  'हंसना', 'हंसा', 'हंसो', 'मुस्कुरा', 'मुस्कुराना', 'मुस्कुराया', 'मुस्कुराओ', 'गा', 'गाना', 'गाया',
  'गाओ', 'नाच', 'नाचना', 'नाचा', 'नाचो', 'कूद', 'कूदना', 'कूदा', 'कूदो', 'गिर',
  'गिरना', 'गिरा', 'गिरो', 'बच', 'बचना', 'बचा', 'बचो', 'मार', 'मारना', 'मारा',
  'मारो', 'पीट', 'पीटना', 'पीटा', 'पीटो', 'लड़', 'लड़ना', 'लड़ा', 'लड़ो', 'जीत',
  'जीतना', 'जीता', 'जीतो', 'हार', 'हारना', 'हारा', 'हारो', 'मिल', 'मिलना', 'मिला',
  'मिलो', 'खो', 'खोना', 'खोया', 'पा', 'पाना', 'पाया', 'पाओ', 'ढूंढ', 'ढूंढना',
  'ढूंढा', 'ढूंढो', 'पकड़', 'पकड़ना', 'पकड़ा', 'पकड़ो', 'छोड़', 'छोड़ना', 'छोड़ा', 'छोड़ो'
];

export const WORDS_LIST_HINDI_HARD = [
  'ज़िंदगी', 'हमेशा', 'कोशिश', 'कामयाबी', 'मंज़िल', 'रास्ता', 'उम्मीद', 'सपने', 'दिमाग', 'दुनिया',
  'मेहनत', 'पढ़ाई', 'शुक्रिया', 'समझ', 'बढ़िया', 'खूबसूरत', 'मोहब्बत', 'तकलीफ', 'मुश्किल', 'परेशानी',
  'जज़्बात', 'विश्वास', 'एहसास', 'नज़रिया', 'परिवार', 'रिश्ते', 'ज़िम्मेदारी', 'फ़र्ज़', 'कर्तव्य', 'हक़',
  'अधिकार', 'इंसाफ़', 'न्याय', 'इंसानियत', 'शराफ़त', 'बदमाशी', 'गुंडा', 'मवाली', 'चोर', 'लुटेरा',
  'डाकू', 'क़ातिल', 'खूनी', 'मुजरिम', 'अपराधी', 'क़ैदी', 'जेल', 'क़ैद', 'सज़ा', 'रिहा',
  'आज़ाद', 'आज़ादी', 'स्वतंत्रता', 'गुलाम', 'गुलामी', 'नौकर', 'मालिक', 'सेठ', 'राजा', 'रानी',
  'वज़ीर', 'सिपाही', 'सेना', 'फ़ौज', 'जंग', 'युद्ध', 'लड़ाई', 'झगड़ा', 'विवाद', 'समझौता',
  'सुलह', 'दोस्ती', 'दुश्मन', 'मित्र', 'शत्रु', 'साथी', 'संगी', 'हमसफ़र', 'हमदर्द', 'हमराज़',
  'जानेमन', 'महबूब', 'आशिक', 'माशूक', 'दीवाना', 'पागल', 'मजनू', 'लैला', 'हीर', 'रांझा',
  'रोमियो', 'जूलियट', 'कहानी', 'किस्सा', 'दास्तान', 'अफ़साना', 'ग़ज़ल', 'नज़्म', 'कविता', 'गीत',
  'संगीत', 'धुन', 'सुर', 'ताल', 'राग', 'नृत्य', 'नाच', 'कला', 'फ़न', 'हुनर',
  'कमाल', 'धमाल', 'बवाल', 'तहलका', 'तूफ़ान', 'भूकंप', 'ज़लज़ला', 'बाढ़', 'सूखा', 'अकाल',
  'महामारी', 'बीमारी', 'इलाज', 'दवा', 'दारू', 'शराब', 'नशा', 'होश', 'बेहोश', 'पागलपन',
  'दीवानगी', 'जुनून', 'शौक़', 'ज़िद्द', 'हठ', 'अहंकार', 'घमंड', 'ग़ुरूर', 'स्वाभिमान', 'इज़्ज़त',
  'आबरू', 'शर्म', 'हया', 'लिहाज़', 'अदब', 'तमीज़', 'तहज़ीब', 'संस्कार', 'परंपरा', 'रिवाज़',
  'प्रथा', 'रीति', 'रीत', 'रवाज', 'त्यौहार', 'उत्सव', 'मेला', 'जलसा', 'महफ़िल', 'शादी',
  'ब्याह', 'निकाह', 'मंगनी', 'सगाई', 'रिश्ता', 'नाता', 'संबंध', 'ताल्लुक', 'जान', 'पहचान',
  'मुलाकात', 'भेंट', 'दर्शन', 'नज़ारा', 'दृश्य', 'मंज़र', 'मौसम', 'फ़िज़ा', 'हवा', 'रुत',
  'बहार', 'पतझड़', 'सर्दी', 'गर्मी', 'बरसात'
];

export const QUOTES_LIST = [
  "The only way to do great work is to love what you do.",
  "Life is what happens when you're busy making other plans.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "In the end, it's not the years in your life that count. It's the life in your years.",
  "Believe you can and you're halfway there.",
  "You must be the change you wish to see in the world.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "Do not go where the path may lead, go instead where there is no path and leave a trail.",
  "It is during our darkest moments that we must focus to see the light.",
  "Whoever is happy will make others happy too.",
  "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "Many of life's failures are people who did not realize how close they were to success when they gave up.",
  "You will face many defeats in life, but never let yourself be defeated.",
  "The only impossible journey is the one you never begin.",
  "In three words I can sum up everything I've learned about life: it goes on.",
  "To live is the rarest thing in the world. Most people exist, that is all.",
  "That it will never come again is what makes life so sweet.",
  "It is never too late to be what you might have been.",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
  "Pain is inevitable. Suffering is optional.",
  "All the world's a stage, and all the men and women merely players.",
  "Be kind, for everyone you meet is fighting a hard battle.",
  "Unable are the loved to die for love is immortality.",
  "Let me live, love, and say it well in good sentences.",
  "Don't let your happiness depend on something you may lose.",
  "We are all broken, that's how the light gets in.",
  "Appreciation is a wonderful thing. It makes what is excellent in others belong to us as well.",
  "Life is tough my darling, but so are you.",
  "Self-awareness and self-love matter. Who we are is how we lead.",
  "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.",
  "The secret of getting ahead is getting started.",
  "If you can dream it, you can do it.",
  "Always remember that you are absolutely unique. Just like everyone else.",
  "Don't judge each day by the harvest you reap but by the seeds that you plant.",
  "Your time is limited, so don't waste it living someone else's life.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "The purpose of our lives is to be happy.",
  "Life is really simple, but we insist on making it complicated.",
  "May you live all the days of your life.",
  "Life itself is the most wonderful fairy tale.",
  "Do not let making a living prevent you from making a life.",
  "Life is ours to be spent, not to be saved.",
  "Keep smiling, because life is a beautiful thing and there's so much to smile about.",
  "Life is a long lesson in humility.",
  "Love the life you live. Live the life you love.",
  "Life is either a daring adventure or nothing at all.",
  "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose."
];
